# Generated by Django 4.2 on 2023-04-15 21:05

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=2500)),
                ('unhrc_number', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('doctor_id', models.ImageField(default=None, null=True, upload_to=user.models.id_upload_to)),
                ('role', models.CharField(choices=[['RF', 'Refugee'], ['DR', 'Doctor']], default='DR', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified_doctor', models.BooleanField(default=False)),
                ('refugee_card', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.validationimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
