# Generated by Django 4.2 on 2023-04-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationimage',
            name='image_name',
        ),
        migrations.AddField(
            model_name='validationimage',
            name='file',
            field=models.ImageField(default=None, null=True, upload_to='upload/refugee'),
        ),
    ]
