# Generated by Django 4.2 on 2023-04-16 02:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_validationimage_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationimage',
            name='folder_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor_id',
            field=models.ImageField(default=None, null=True, upload_to='uploads/doctor'),
        ),
        migrations.AlterField(
            model_name='validationimage',
            name='file',
            field=models.ImageField(default=None, null=True, upload_to=user.models.id_upload_to),
        ),
    ]
