# Generated by Django 4.2 on 2023-04-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_validationimage_folder_name_alter_user_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctor_id',
            field=models.ImageField(default=None, null=True, upload_to='upload/doctor'),
        ),
    ]
