# Generated by Django 4.2 on 2023-04-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
