# Generated by Django 4.2 on 2023-04-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0005_remove_scheduledslot_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledslot',
            name='slug',
        ),
    ]
